"use client";

import { useState } from "react";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { SectionHeader, Pill } from "@/components/ui";

export default function PacketsPage() {
  const { sources, selected, packets, refreshPackets, flash } = useWorkspace();
  const [question, setQuestion] = useState("What makes a source-based research workflow compound over time?");
  const [title, setTitle] = useState("Untitled packet");
  const [busy, setBusy] = useState(false);

  const selectedSources = sources.filter((s) => selected.includes(s.id));

  async function generate() {
    if (selectedSources.length < 2) {
      flash("Select at least two sources in the Library to create a research packet.");
      return;
    }
    setBusy(true);
    try {
      const res = await fetch("/api/packets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sourceIds: selected, question, title }),
      });
      const data = await res.json();
      if (!res.ok) {
        flash(data.error || "Packet generation failed.");
        return;
      }
      await refreshPackets();
      flash("Packet brief generated by Gemini.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="space-y-7">
      <SectionHeader
        eyebrow="Research packets / synthesis"
        title="Make the evidence legible."
        description="A packet is a Gemini-synthesized, source-attributed brief built from the video titles of your selected sources."
        action={
          <button onClick={generate} disabled={busy} className="ytpr-primary-button disabled:opacity-60">
            {busy ? "Synthesizing…" : "Generate packet"} <span>↗</span>
          </button>
        }
      />
      <div className="grid gap-4 xl:grid-cols-[0.8fr_1.2fr]">
        <section className="ytpr-panel p-5">
          <label className="text-xs font-medium text-[#f4f0e8]">
            Packet title
            <input value={title} onChange={(e) => setTitle(e.target.value)} className="ytpr-input mt-2" />
          </label>
          <label className="mt-4 block text-xs text-[#8f97a5]">
            Research question
            <textarea value={question} onChange={(e) => setQuestion(e.target.value)} className="ytpr-textarea mt-2 min-h-[120px]" />
          </label>
        </section>
        <section className="ytpr-panel p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-[11px] uppercase tracking-[0.18em] text-[#ef765e]">Source set</p>
              <h2 className="mt-1 text-lg text-[#f4f0e8]">{selectedSources.length} sources in brief</h2>
            </div>
            <Pill tone={selectedSources.length > 1 ? "accent" : "warm"}>
              {selectedSources.length > 1 ? "Ready to synthesize" : "Select 2+ sources in Library"}
            </Pill>
          </div>
          <div className="mt-5 space-y-2">
            {selectedSources.map((source) => (
              <div key={source.id} className="rounded-lg border border-[#303541] bg-[#20232b] p-3">
                <p className="text-sm text-[#f4f0e8]">{source.title}</p>
                <p className="mt-1 text-xs text-[#8f97a5]">
                  {source.videos.length} videos · {source.transcript}
                </p>
              </div>
            ))}
            {selectedSources.length === 0 && <p className="text-sm text-[#8f97a5]">Nothing selected yet.</p>}
          </div>
        </section>
      </div>
      <section className="space-y-4">
        <p className="text-[11px] uppercase tracking-[0.18em] text-[#ef765e]">Generated packets</p>
        {packets.length === 0 && <p className="text-sm text-[#8f97a5]">No packets yet.</p>}
        {packets.map((packet) => (
          <div key={packet.id} className="ytpr-panel p-5">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-medium text-[#f4f0e8]">{packet.title}</h3>
              <span className="text-xs text-[#737b8a]">{new Date(packet.createdAt).toLocaleString()}</span>
            </div>
            <p className="mt-1 text-xs text-[#8f97a5]">{packet.question}</p>
            <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#c3c7cf]">{packet.brief}</p>
          </div>
        ))}
      </section>
    </div>
  );
}
