"use client";

import { useState } from "react";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { SectionHeader, Pill } from "@/components/ui";

const SURFACES: { key: "shorts" | "linkedin" | "x" | "newsletter"; title: string; body: string; glyph: string }[] = [
  { key: "shorts", title: "YouTube Shorts", body: "Hook, retention beats, on-screen text", glyph: "◉" },
  { key: "linkedin", title: "LinkedIn", body: "Professional insight post", glyph: "in" },
  { key: "x", title: "X thread", body: "6–8 concise source-backed posts", glyph: "𝕏" },
  { key: "newsletter", title: "Newsletter", body: "Context-rich excerpt", glyph: "✉" },
];

export default function RepurposePage() {
  const { sources, flash } = useWorkspace();
  const [sourceId, setSourceId] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  const [draft, setDraft] = useState<{ kind: string; text: string } | null>(null);

  const source = sources.find((s) => s.id === sourceId) ?? sources[0];

  async function generate(kind: (typeof SURFACES)[number]["key"]) {
    if (!source) {
      flash("Collect a source first.");
      return;
    }
    setBusy(kind);
    setDraft(null);
    try {
      const res = await fetch("/api/repurpose", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sourceId: source.id, kind }),
      });
      const data = await res.json();
      if (!res.ok) {
        flash(data.error || "Draft generation failed.");
        return;
      }
      setDraft({ kind, text: data.draft });
    } finally {
      setBusy(null);
    }
  }

  return (
    <div className="space-y-7">
      <SectionHeader
        eyebrow="Repurpose / Gemini drafts"
        title="One source, many surfaces."
        description="Drafts are generated by Gemini from the source's video titles — title-based, not full-transcript-based, so verify specifics before publishing."
        action={
          <select value={source?.id ?? ""} onChange={(e) => setSourceId(e.target.value)} className="ytpr-input w-64">
            {sources.length === 0 && <option value="">No sources yet</option>}
            {sources.map((s) => (
              <option key={s.id} value={s.id}>
                {s.title}
              </option>
            ))}
          </select>
        }
      />
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {SURFACES.map((surface) => (
          <button
            key={surface.key}
            onClick={() => generate(surface.key)}
            disabled={busy !== null || !source}
            className="ytpr-panel p-5 text-left transition hover:-translate-y-0.5 hover:border-[#ef765e] disabled:opacity-60"
          >
            <span className="text-xl text-[#ef765e]">{surface.glyph}</span>
            <h2 className="mt-6 text-base font-medium text-[#f4f0e8]">{surface.title}</h2>
            <p className="mt-2 text-xs leading-5 text-[#8f97a5]">{surface.body}</p>
            <p className="mt-5 text-[11px] text-[#8de0ed]">{busy === surface.key ? "Generating…" : "Generate draft →"}</p>
          </button>
        ))}
      </div>
      {draft && (
        <section className="ytpr-panel p-5">
          <div className="flex items-center justify-between">
            <p className="text-[11px] uppercase tracking-[0.18em] text-[#ef765e]">Draft · {draft.kind}</p>
            <Pill tone="accent">Source: {source?.title.slice(0, 30)}</Pill>
          </div>
          <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#c3c7cf]">{draft.text}</p>
        </section>
      )}
    </div>
  );
}
